# Generated by Django 5.1.6 on 2025-02-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="custom_source",
        ),
        migrations.RemoveField(
            model_name="income",
            name="user",
        ),
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="income",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                    ("Partially Paid", "Partially Paid"),
                    ("Due", "Due"),
                    ("Processing", "Processing"),
                    ("On Hold", "On Hold"),
                    ("Refunded", "Refunded"),
                    ("Overdue", "Overdue"),
                ],
                max_length=50,
            ),
        ),
    ]
